version: '3'

services:
  apache:
    image: php:8.2-apache
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    command: 
      - bash
      - -c
      - |
        docker-php-ext-install pdo pdo_mysql
        apache2-foreground

  mariadb:
    image: mariadb:10.6
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: